### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by StarLederer** [b-fuze/deno-dom#143]
It looks like [Namespaces](https://www.w3.org/TR/1999/WD-DOM-Level-2-19990719/namespaces.html) are not currently supported.

Namespaces are not too common but are still sometimes found useful, e.g. when working with [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG), [OOXML](http://officeopenxml.com/) or other non-HTML XML formats.

Would it be possible to add support for this feature and implement functions such as `createAttributeNS`, `createElementNS`, `setAttributeNS` etc. so that deno-dom can be used in libraries that build and manipulate exotic (or not so much) XML formats?

**Comment by StarLederer** [comment]
Might be a duplicate of #140 but that one focuses entirely on CSS

**Comment by rgbkrk** [comment]
Thanks for making the issue. I'm really curious about being able to run plotting libraries server side like this:

```typescript
import { DOMParser } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";
import * as Plot from "npm:@observablehq/plot"

const document = new DOMParser().parseFromString(
  `<html>
    <body>
      <div id="root" />
    </body>
  </html>`,
  "text/html",
);

Plot.barY(alphabet, {x: "letter", y: "frequency"}).plot({document})
```

which inevitably needs `createElementNS` to work for SVG:

```
Error: createElementNS: "http://www.w3.org/2000/svg" namespace unimplemented
    at HTMLDocument.createElementNS (https://deno.land/x/deno_dom@v0.1.38/src/dom/document.ts:244:13)
    at Element.<anonymous> (file:///Users/kai/Library/Caches/deno/npm/registry.npmjs.org/d3-selection/3.0.0/src/creator.js:16:31)
    at plot (file:///Users/kai/Library/Caches/deno/npm/registry.npmjs.org/@observablehq/plot/0.6.10/src/plot.js:156:30)
    at BarY.plotThis [as plot] (file:///Users/kai/Library/Caches/deno/npm/registry.npmjs.org/@observablehq/plot/0.6.10/src/plot.js:370:10)
    at <anonymous>:12:4: 
```

**Comment by b-fuze** [comment]
> Might be a duplicate of https://github.com/b-fuze/deno-dom/issues/140 but that issue focuses entirely on CSS while this one entirely on the DOM

No, it's not a duplicate of that issue. But it does coincide with that issue + #73 in general. I want to add XML support which will also require implementing namespaces as well

**Comment by StarLederer** [comment]
Awesome! Really looking forward to it

**Comment by cornelius-dol** [comment]
I came here looking for the current state of NS support, solely because I use Deno + deno-dom to unit test a vDOM library. I just need simple support for it setting the `xmlns` attribute so I can confirm correct DOM generation. I wonder if that might be a simple first step?
