### ISSUE TITLE
Is deno-dom compatible with DOM lib?

### ISSUE THREAD

**Issue by quaos** [b-fuze/deno-dom#31]
Hello,

I'm trying to use this with React and DOM lib, but there seemed to be some conflicts:

```
error: TS2322 [ERROR]: Type '(_html: string) => void' is not assignable to type 'Parser'.
  Type 'void' is not assignable to type 'string'.
export let parse: Parser = (_html) => {
           ~~~~~
    at https://deno.land/x/deno_dom@v0.1.3-alpha2/src/parser.ts:5:12

TS2304 [ERROR]: Cannot find name 'Deno'.
  Deno.exit(1);
  ~~~~
    at https://deno.land/x/deno_dom@v0.1.3-alpha2/src/parser.ts:7:3

TS2322 [ERROR]: Type '(_html: string) => void' is not assignable to type 'Parser'.
  Type 'void' is not assignable to type 'string'.
export let parseFrag: Parser = (_html) => {
           ~~~~~~~~~
    at https://deno.land/x/deno_dom@v0.1.3-alpha2/src/parser.ts:10:12

TS2304 [ERROR]: Cannot find name 'Deno'.
  Deno.exit(1);
  ~~~~
    at https://deno.land/x/deno_dom@v0.1.3-alpha2/src/parser.ts:12:3

TS2322 [ERROR]: Type 'Node' is not assignable to type 'string | Node'.
  Type 'Node' is missing the following properties from type 'Node': baseURI, firstChild, isConnected, lastChild, and 30 more.
                source = rootNode;
                ~~~~~~
    at file:///..../src/transformer.ts:36:17
```

My tsconfig.json file:
```json
{
  "compilerOptions": {
    "isolatedModules": false,
    "allowJs": false,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "checkJs": false,
    "jsx": "react",
    "jsxFactory": "React.createElement",
    "lib": ["DOM", "ESNext"],
    "noFallthroughCasesInSwitch": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitUseStrict": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "removeComments": false,
    "strict": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "suppressExcessPropertyErrors": false,
    "suppressImplicitAnyIndexErrors": false
  },
  "deno": true
}
```

So I'd like to know if this library is compatible with Deno's TS DOM library or not.
Thanks!

**Comment by b-fuze** [comment]
Theoretically it _is_ possibly to do, however, officially we don't support it. It is planned, but not planned specifically for React.

**Comment by b-fuze** [comment]
I can't fully help with this issue, but if you omit the `tsconfig.json` file and stick with a `.jsx` file while importing React it _may_ work. Though React likely expects some `Window` globals and things (like `document`) so I can't guarantee anything.

**Comment by quaos** [comment]
Thanks for the answer.

BTW, `lib.dom.d.ts` is not React specific thing, but a browser DOM API typedef defined in Deno.

**Comment by quaos** [comment]
@b-fuze I somehow managed to make this work.

in ***tsconfig.json***
```js
{
    // ...
    "lib": [
      "dom",
      "deno.ns",
      "esnext"
    ],
    // ...
}
```

in ***dom-polyfill.ts*** (imported by main code)

```typescript
import { DOMParser as DenoDomParser } from "https://deno.land/x/deno_dom@####/deno-dom-wasm.ts";";

globalThis.DOMParser = globalThis.DOMParser || DenoDomParser;

export {}
```

I suppose you can close this issue now.
