### ISSUE TITLE
TypeError: a.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by oscarotero** [b-fuze/deno-dom#41]
Hi.
I have this selector: `document.querySelectorAll("a,link")` and it returns the following error:

```
TypeError: a.compareDocumentPosition is not a function
    at documentOrder (https://deno.land/x/deno_dom@v0.1.8-alpha/src/dom/nwsapi.js:203:16)
    at Array.sort (<anonymous>)
    at collect (https://deno.land/x/deno_dom@v0.1.8-alpha/src/dom/nwsapi.js:1564:17)
    at Object._querySelectorAll [as select] (https://deno.land/x/deno_dom@v0.1.8-alpha/src/dom/nwsapi.js:1516:36)
    at HTMLDocument.querySelectorAll (https://deno.land/x/deno_dom@v0.1.8-alpha/src/dom/document.ts:205:33)
    at processor (file:///Users/oscarotero/www/lumeland/test/lume/plugins/relative_urls.js:29:10)
```

Doing two independent selections works fine `document.querySelectorAll("a")` and `document.querySelectorAll("link")`, but one query including both selectors fails.

**Comment by b-fuze** [comment]
Thanks
