### ISSUE TITLE
deno-dom-native breaks on M1

### ISSUE THREAD

**Issue by fserb** [b-fuze/deno-dom#71]
Whe I try to import deno-dom-native on M1, I get:
```
error: Uncaught (in promise) Error: Could not open library: Could not open library: dlopen(/Users/fserb/Library/Caches/deno/plug/https/github.com/46ee472b4f7af1e50525e80feba202b06b349053f8dd4d0346878fd6
80f9cc10.dylib, 0x0005): tried: '/Users/fserb/Library/Caches/deno/plug/https/github.com/46ee472b4f7af1e50525e80feba202b06b349053f8dd4d0346878fd680f9cc10.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/46ee472b4f7af1e50525e80feba202b06b349053f8dd4d0346878fd680f9cc10.dylib' (no such file), '/usr/lib/46ee472b4f7af1e50525e80feba202b06b349053f8dd4d0346878fd680f9cc10.dylib' (no such file)
  return Deno.dlopen(file.path, symbols);
              ^
    at Object.opSync (deno:core/01_core.js:142:12)
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:15:24)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:63:12)
    at Module.prepare (https://deno.land/x/plug@0.4.1/plug.ts:77:15)
    at async https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:30:11
```

**Comment by b-fuze** [comment]
It's a problem with my Deno DOM releases. I only have x86_64 releases and haven't made any for other architectures... I'll need to fix up my release process to enable ARM64 for both macOS and Linux, and maybe at some point, Windows.
