### ISSUE TITLE
Type-checking errors with Deno v1.17.1

### ISSUE THREAD

**Issue by jjallaire** [b-fuze/deno-dom#78]
I'm noticing a bunch of type-checking errors when running deno-dom 0.1.17 against the latest deno release (v1.17.1):

```
error: TS2344 [ERROR]: Type 'DeepWriteable<{ readonly deno_dom_usize_len: { readonly parameters: readonly []; readonly result: "usize"; }; readonly deno_dom_parse_sync: { readonly parameters: readonly ["buffer", "usize", "buffer"]; readonly result: "void"; }; readonly deno_dom_parse_frag_sync: { ...; }; readonly deno_dom_is_big_endian: { ...; }...' does not satisfy the constraint 'Record<string, ForeignFunction>'.
  Property 'deno_dom_parse_sync' is incompatible with index signature.
    Type 'DeepWriteable<{ readonly parameters: readonly ["buffer", "usize", "buffer"]; readonly result: "void"; }>' is not assignable to type 'ForeignFunction'.
      Types of property 'parameters' are incompatible.
        Type '["buffer", "usize", "buffer"]' is not assignable to type 'NativeType[]'.
          Type '"buffer" | "usize"' is not assignable to type 'NativeType'.
            Type '"buffer"' is not assignable to type 'NativeType'.
let dylib: Deno.DynamicLibrary<typeof symbols>;
                               ~~~~~~~~~~~~~~
    at https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:23:32

TS2322 [ERROR]: Type 'DynamicLibrary<Record<string, ForeignFunction>>' is not assignable to type 'DynamicLibrary<DeepWriteable<{ readonly deno_dom_usize_len: { readonly parameters: readonly []; readonly result: "usize"; }; readonly deno_dom_parse_sync: { readonly parameters: readonly ["buffer", "usize", "buffer"]; readonly result: "void"; }; readonly deno_dom_parse_frag_sync: { ...; }; readonly deno_dom_is_big_e...'.
  Types of property 'symbols' are incompatible.
    Type '{ [x: string]: (...args: unknown[]) => unknown; }' is missing the following properties from type '{ deno_dom_usize_len: (...args: unknown[]) => unknown; deno_dom_parse_sync: (...args: unknown[]) => unknown; deno_dom_parse_frag_sync: (...args: unknown[]) => unknown; deno_dom_is_big_endian: (...args: unknown[]) => unknown; deno_dom_copy_buf: (...args: unknown[]) => unknown; }': deno_dom_usize_len, deno_dom_parse_sync, deno_dom_parse_frag_sync, deno_dom_is_big_endian, deno_dom_copy_buf
  dylib = Deno.dlopen(denoNativePluginPath, symbols);
  ~~~~~
    at https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:27:3

TS2345 [ERROR]: Argument of type 'DeepWriteable<{ readonly deno_dom_usize_len: { readonly parameters: readonly []; readonly result: "usize"; }; readonly deno_dom_parse_sync: { readonly parameters: readonly ["buffer", "usize", "buffer"]; readonly result: "void"; }; readonly deno_dom_parse_frag_sync: { ...; }; readonly deno_dom_is_big_endian: { ...; }...' is not assignable to parameter of type 'Record<string, ForeignFunction>'.
  dylib = Deno.dlopen(denoNativePluginPath, symbols);
                                            ~~~~~~~
    at https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:27:45

TS2322 [ERROR]: Type 'DynamicLibrary<Record<string, ForeignFunction>>' is not assignable to type 'DynamicLibrary<DeepWriteable<{ readonly deno_dom_usize_len: { readonly parameters: readonly []; readonly result: "usize"; }; readonly deno_dom_parse_sync: { readonly parameters: readonly ["buffer", "usize", "buffer"]; readonly result: "void"; }; readonly deno_dom_parse_frag_sync: { ...; }; readonly deno_dom_is_big_e...'.
  dylib = await Plug.prepare({
  ~~~~~
    at https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:30:3

TS2345 [ERROR]: Argument of type 'DeepWriteable<{ readonly deno_dom_usize_len: { readonly parameters: readonly []; readonly result: "usize"; }; readonly deno_dom_parse_sync: { readonly parameters: readonly ["buffer", "usize", "buffer"]; readonly result: "void"; }; readonly deno_dom_parse_frag_sync: { ...; }; readonly deno_dom_is_big_endian: { ...; }...' is not assignable to parameter of type 'Record<string, ForeignFunction>'.
  }, symbols);
     ~~~~~~~
    at https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:33:6

Found 5 errors.
```

Thinking that these might be "merely" apparently incompatible types that were in fact okay, I added `--no-check=remote` and then see this at runtime:

```
error: Uncaught (in promise) TypeError: Error parsing args: unknown variant `buffer`, expected one of `void`, `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64`, `usize`, `isize`, `f32`, `f64`, `pointer`
  dylib = Deno.dlopen(denoNativePluginPath, symbols);
               ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:150:24)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:228:12)
    at https://deno.land/x/deno_dom@v0.1.17-alpha/deno-dom-native.ts:27:16
```

**Comment by b-fuze** [comment]
Well I'll be... Seems they switched up the native API yet again lol... I'll fix that

**Comment by b-fuze** [comment]
I missed the part in the release notes where they said they "renamed `buffer` to `pointer`"

**Comment by jjallaire** [comment]
Thanks!!! I noticed that the binaries being downloaded are still from 0.1.17-alpha: https://github.com/b-fuze/deno-dom/blob/master/deno-dom-native.ts#L32. It is okay to use these binaries with the 0.1.20 typescript?

**Comment by b-fuze** [comment]
@jjallaire yes, the binaries don't need to change. It was just the JS FFI API that changed

**Comment by jjallaire** [comment]
Okay, great, thanks again!
